name: Test Periodic Changelog
on:
  workflow_dispatch:
jobs:
  periodic-changelog: # Note: Uses 'dist' build.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./
