name: Validate
on:
  push:
    branches: [main]
  pull_request:
jobs:
  validate:
    name: 🧹 Validate
    runs-on: ubuntu-20.04
    steps:
    - name: Setup up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
    
    - name: Lint
      run: npm run lint-check

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build
